/*############################################################################
  # Copyright 2018 Intel Corporation
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
  ############################################################################*/
/*!
 * \file
 * \brief Test data.
 *
 * Type    : Intel(R) EPID 2.0 private f
 */
//unsigned char f[] = {
  0xb2, 0x17, 0x61, 0x7d, 0x51, 0x64, 0xf6, 0xa4,
  0xbc, 0x97, 0xcd, 0x67, 0xde, 0x98, 0xce, 0xee,
  0x8d, 0x5e, 0x78, 0x84, 0x77, 0x9b, 0x99, 0x84,
  0x01, 0x9f, 0x66, 0x7c, 0xd4, 0x67, 0x81, 0x48
//};
//unsigned int nonce_dat_len = 32;
