/*############################################################################
  # Copyright 2018-2019 Intel Corporation
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
  ############################################################################*/
/*!
 * \file
 * \brief Test data.
 *
 * Type    : Intel(R) EPID 2.0 issuer nonce
 */
//unsigned char nonce_dat[] = {
  0xd3, 0x6d, 0xb5, 0xe0, 0x7f, 0x4c, 0xfd, 0x35, 0x4e, 0xac, 0x7b, 0x17, 0x68, 0x3d, 0x51, 0x91,
  0x41, 0x89, 0x3c, 0x5e, 0x39, 0x5f, 0xd1, 0xed, 0x63, 0x22, 0x6b, 0x27, 0x9a, 0x5d, 0x48, 0xf1,
//};
//unsigned int nonce_dat_len = 32;
