/*############################################################################
  # Copyright 2018 Intel Corporation
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
  ############################################################################*/
/*!
 * \file
 * \brief Test data.
 *
 * Type    : Intel(R) EPID 2.0 issuer nonce
 */
//unsigned char nonce2_dat[] = {
  0x42, 0xb6, 0xca, 0xc0, 0x91, 0xb5, 0x76, 0x65, 0x07, 0x7e, 0x34, 0x38,
  0x3d, 0x11, 0x67, 0xde, 0x78, 0xef, 0x0b, 0x9f, 0x69, 0xc1, 0x9c, 0x7b,
  0xc2, 0xf6, 0xdd, 0xbf, 0xd5, 0xf0, 0xa3, 0x88
//};
//unsigned int nonce2_dat_len = 32;
